package com.prowidesoftware.swift.model.mx;

import java.nio.file.Files;
import java.nio.file.Paths;

public class GeneratePacs029 {
    public static void main(String[] args) throws Exception {
        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<Document xmlns=\"urn:iso:std:iso:20022:tech:xsd:pacs.029.001.02\">\n"
                + "    <MulSttlmReq>\n"
                + "        <GrpHdr>\n"
                + "            <MsgId>MSGID123</MsgId>\n"
                + "            <CreDtTm>2023-10-01T12:00:00Z</CreDtTm>\n"
                + "            <NbOfSttlmReqs>1</NbOfSttlmReqs>\n"
                + "        </GrpHdr>\n"
                + "        <SttlmReq>\n"
                + "            <InstrId>INSTRID123</InstrId>\n"
                + "            <NbOfMvmntRcrds>2</NbOfMvmntRcrds>\n"
                + "            <MvmntRcrd>\n"
                + "                <Id>MVMNT123</Id>\n"
                + "                <SeqNb>1</SeqNb>\n"
                + "                <Amt>\n"
                + "                    <Amt Ccy=\"EUR\">100.00</Amt>\n"
                + "                    <CdtDbt>CRDT</CdtDbt>\n"
                + "                </Amt>\n"
                + "                <Ptcpt>\n"
                + "                    <Id>\n"
                + "                        <OrgId>\n"
                + "                            <AnyBIC>BANKGB22</AnyBIC>\n"
                + "                        </OrgId>\n"
                + "                    </Id>\n"
                + "                </Ptcpt>\n"
                + "                <PtcptAcct>\n"
                + "                    <Id>\n"
                + "                        <Othr>\n"
                + "                            <Id>ACC123</Id>\n"
                + "                        </Othr>\n"
                + "                    </Id>\n"
                + "                </PtcptAcct>\n"
                + "            </MvmntRcrd>\n"
                + "            <MvmntRcrd>\n"
                + "                <Id>MVMNT124</Id>\n"
                + "                <SeqNb>2</SeqNb>\n"
                + "                <Amt>\n"
                + "                    <Amt Ccy=\"EUR\">100.00</Amt>\n"
                + "                    <CdtDbt>DBIT</CdtDbt>\n"
                + "                </Amt>\n"
                + "                <Ptcpt>\n"
                + "                    <Id>\n"
                + "                        <OrgId>\n"
                + "                            <AnyBIC>BARCGB22</AnyBIC>\n"
                + "                        </OrgId>\n"
                + "                    </Id>\n"
                + "                </Ptcpt>\n"
                + "                <PtcptAcct>\n"
                + "                    <Id>\n"
                + "                        <Othr>\n"
                + "                            <Id>ACC124</Id>\n"
                + "                        </Othr>\n"
                + "                    </Id>\n"
                + "                </PtcptAcct>\n"
                + "            </MvmntRcrd>\n"
                + "        </SttlmReq>\n"
                + "    </MulSttlmReq>\n"
                + "</Document>";
        Files.write(Paths.get("iso20022-core/src/test/resources/pacs.029.001.02.xml"), xml.getBytes());
        System.out.println("Generated pacs.029.001.02.xml");
    }
}
